### ISSUE TITLE
Breaks in Release mode using a gridview layout

### ISSUE THREAD

**Issue by scottwojan** [paulpatarinski/Xamarin.Forms.Plugins#61] opened 2015-09-15 16:53 UTC
https://www.dropbox.com/s/mmgkan2eobylg03/KeyboardTest.zip?dl=0

The attached solution has a form using a gridview.  The odd thing is that it works in debug mode but doesn't in Release.  I'd really appreciate any help you could provide.

**Comment by paulpatarinski** [comment] 2015-09-22 01:09
Hey Scott. I was trying to reproduce this with the attached sample, but was not able to in Debug or Release using the Simulator. Are you seeing this both on device and sim? This is the UI I should expect to see right :


![ios simulator screen shot sep 21 2015 8 06 09 pm](https://cloud.githubusercontent.com/assets/7964134/10009024/3bb9da74-609c-11e5-9bf0-8036043c7cfd.png)

**Comment by scottwojan** [comment] 2015-09-22 01:13
Yes it was doing it in the sim in Release mode.  When you click the license input the keyboard overlays it.

Sent from my iPhone

On Sep 21, 2015, at 8:09 PM, Paul P <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Scott. I was trying to reproduce this with the attached sample, but was not able to in Debug or Release using the Simulator. Are you seeing this both on device and sim? This is the UI I should expect to see right :

[ios simulator screen shot sep 21 2015 8 06 09 pm]<https://cloud.githubusercontent.com/assets/7964134/10009024/3bb9da74-609c-11e5-9bf0-8036043c7cfd.png>

-

**Comment by paulpatarinski** [comment] 2015-09-22 12:41
This is what I see in release mode, keyboard does not overlap the entry field.

![ios simulator screen shot sep 22 2015 7 38 54 am](https://cloud.githubusercontent.com/assets/7964134/10018509/001819ca-60fd-11e5-9795-f89ee6c0c822.png)

The only way I could get it to overlap is if I tap the State entry first, then WITHOUT tapping away tap the License # entry

**Comment by scottwojan** [comment] 2015-09-22 17:14
Okay so it looks like it's not doing it in the sim but definitely is on an actual device.  The attached screenshot shows the overlay of the keyboard.  Click in state and then click in license, the keyboard blocks it.

[image1.PNG]

Sent from my iPhone

On Sep 22, 2015, at 7:42 AM, Paul P <notifications@github.com<mailto:notifications@github.com>> wrote:


This is what I see in release mode, keyboard does not overlap the entry field.

[ios simulator screen shot sep 22 2015 7 38 54 am]<https://cloud.githubusercontent.com/assets/7964134/10018509/001819ca-60fd-11e5-9795-f89ee6c0c822.png>

The only way I could get it to overlap is if I tap the State entry first, then WITHOUT tapping away tap the License # entry

-

**Comment by scottwojan** [comment] 2015-09-28 14:30
Paul, were you able to replicate?

**Comment by paulpatarinski** [comment] 2015-09-29 02:24
Sorry @scottwojan I am not able to replicate. 

Using this project : https://drive.google.com/file/d/0By1OWryhO3RPMC1fWVg1d0JDZlk/view?usp=sharing

When I run on my iPhone 6 Plus using iOS 9.01 this is what I see : 

![img_1232](https://cloud.githubusercontent.com/assets/7964134/10153956/367236b6-6627-11e5-91cc-5c2ad5349d57.jpg)

![img_1233](https://cloud.githubusercontent.com/assets/7964134/10153955/365eddfa-6627-11e5-837c-31d7893992e8.jpg)

**Comment by scottwojan** [comment] 2015-10-01 02:09
Paul, could you please review this one?  Attached is a screenshot of the issue on my iPhone 6 with iOS 8.4.1.  It was built in release mode.

https://www.dropbox.com/s/mmgkan2eobylg03/KeyboardTest.zip?dl=0

![keyboard](https://cloud.githubusercontent.com/assets/10407473/10211297/54dd6fa8-67b7-11e5-8939-eaaadc74734b.jpeg)

**Comment by scottwojan** [comment] 2015-10-01 20:16
This is an iPhone 5s with iOS 9.  Still blocking the input.

**Comment by russellharvey** [comment] 2015-11-06 03:13
I'm experiencing the same difficulty across an iPhone 6 running iOS 8.x and an iPhone 6s running iOS 9.1.  No GridViews present, just several StackLayouts with an Entry at the bottom of the main layout.  

Works fine in the simulator in all modes, and works fine on devices in Debug mode, but the keyboard occludes the Entry in Release mode.

**Comment by scottwojan** [comment] 2015-11-06 03:19
Unregister the nuget plugin and put his classes I'm your project directly and see if that works.  That's the only thing that worked for me!

Sent from my iPhone

On Nov 5, 2015, at 9:13 PM, russellharvey <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm experiencing the same difficulty across an iPhone 6 running iOS 8.x and an iPhone 6s running iOS 9.1. No GridViews present, just several StackLayouts with an Entry at the bottom of the main layout.

Works fine in the simulator in all modes, and works fine on devices in Debug mode, but the keyboard occludes the Entry in Release mode.

-

**Comment by russellharvey** [comment] 2015-11-06 23:31
Worked like a charm when using the classes directly.  Most perplexing.

**Comment by paulpatarinski** [comment] 2016-01-04 03:41
This is fixed in 1.0.3. It was due to linking in Release mode removing the plugin. 
https://www.nuget.org/packages/Xam.Plugins.Forms.KeyboardOverlap/

**Closed by paulpatarinski** 2016-01-04 03:41 UTC
Labels: KeyboardOverlap
