### ISSUE TITLE
SVG: Could not load type from assembly

### ISSUE THREAD

**Issue by JoshuaNovak919** [paulpatarinski/Xamarin.Forms.Plugins#32] opened 2015-05-14 05:34 UTC
I am using the SVG plugin along with NControl and for some reason now I am getting this error when I try to load an SVG: 

`Could not load type 'NGraphics.Parsers.SvgReader' from assembly 'NGraphics, Version=1.0.5587.13975, Culture=neutral, PublicKeyToken=null'.`

Anyone have any ideas why?

**Comment by paulpatarinski** [comment] 2015-05-31 19:17
@JoshuaNovak919 I will have to fix a couple other bugs before I get to this. But I am using NGraphics within the SVG control, so my guess is that there is a version conflict with both assemblies being referenced. Probably when you added the NControl reference the NGraphics Custom assembly that the SVG plugin depends on got removed.

**Comment by paulpatarinski** [comment] 2015-06-07 17:38
@JoshuaNovak919 this should be fixed in version >= 1.0.0.23. I am now using a Custom suffix for the NGraphics dlls, so hopefully that will avoid the overlap. If not I will have to update the namespaces as well. Let me know if the issue is resolved

**Closed** 2015-06-07 18:53 UTC
Labels: SVG

**Comment by JoshuaNovak919** [comment] 2015-06-07 21:42
@paulpatarinski Looks like it's good to go. Thanks!
